package com.hjtech.secretary.utils;

public enum JsonTarget{
	MEET_LIST, MY_MEET, VERIFY_CODE, VALIDATION, REGISTER, LOGIN, METTING_DETAILS, COLLECT, ENROLL, COMMENT, ADD_COMMENT, RELATED_METTING, MESSAGE, SIGNIN
}
